### ISSUE TITLE
Windows 64bit

### ISSUE THREAD

**Issue by ShadowUchiha** [jrjparks/myManga#23]
Hello, I'm a new user to this program and after downloading the first release it wont start then seeing its 32bit is there a way to fix this I'm using a 64bit windows 10.

**Comment by jrjparks** [comment]
I can assure you that x64 Windows can and will run x32 programs. Have you followed [**these**](/jrjparks/myManga#installing) steps after downloading? If it is crashing there should be a log file of the crash, could you [**upload**](http://pastebin.com/) it and share it?

**Comment by ShadowUchiha** [comment]
Oh I see what I did wrong now I downloaded the latest without reading the
instructions.

On Fri, Dec 18, 2015 at 12:31 PM, James R.J. Parks <notifications@github.com
