### ISSUE TITLE
dlls in plugins are preventing the start of myManga

### ISSUE THREAD

**Issue by Flanisch** [jrjparks/myManga#26]
I'm using windows 10 64bit, .net framework 4.6.1, (if relevant) System Language german. Found an errorlog in /Logs, which I attached. I tried deleting the dlls in /plugins one by one and starting myManga after deleting one. The Logs are roughly the same, just the next dll in alphabetical order is preventing a successfull launch, thus appearing in the log. After deleting every dll in /plugins, the program launches successfull. I hope you can fix this issue.
[mymanga_log.txt](https://github.com/jrjparks/myManga/files/114693/mymanga_log.txt)

**Comment by jrjparks** [comment]
Okay, so it looks like a few people are having this issue.
[Download this file](https://github.com/jrjparks/myManga/releases/download/v3.0.5859.38362/myManga.exe.config) and save it in the same directory as myManga.exe

**Comment by jrjparks** [comment]
Whoops, sorry about that. That is usually what fixes that error, although I did add a few extra line that shouldn't have been there. Try [re-downloading that file](https://github.com/jrjparks/myManga/releases/download/v3.0.5859.38362/myManga.exe.config).

**Comment by Flanisch** [comment]
Now it works, thank you :)
