### ISSUE TITLE
EXE Shows in Task Manager, but won't open on screen

### ISSUE THREAD

**Issue by dreadbcool4ever** [jrjparks/myManga#32]
Hey.

I have seen this issue before, but I have tried, and I have updated my .NET frameworks to 4.6.1, and nothing at all. Need some help.

Log:
http://pastebin.com/PcwsmNXX

Please help me solve this, so I can read all of my wonderful Manga again.

Sincerely,
Dread

**Comment by jrjparks** [comment]
I should be posting a update in a few days that should fix a few things and add some new features.
But this seems like you need to download the [myManga.exe.config](https://github.com/jrjparks/myManga/releases/download/v3.0.5859.38362/myManga.exe.config) file and add it to the myManga directory.

**Comment by dreadbcool4ever** [comment]
@jrjparks Thanks. Didn't even notice it was needed. Got it working, so now I can read. Thanks a lot, and can't wait to see that update of yours.

Sincerely,
Dread
