### ISSUE TITLE
Black pages after download

### ISSUE THREAD

**Issue by DDraper95** [jrjparks/myManga#43]
After downloading a manga most of / if not all of the pages are just black.

**Comment by jrjparks** [comment]
Error log? Have you tried to re-download the chapter? Can you read the chapter normally on the website? More information is required.

**Comment by DDraper95** [comment]
http://pastebin.com/c8GzVnm5
Tried re-downloading either made any chapters with partially lost pages lose them all. I can read them online as normal.

**Comment by DDraper95** [comment]
Re-downloaded the app seems to have fixed it. Hope that helps locate some sort of problem downloading the program and manga again is gonna be a pain.

**Comment by jrjparks** [comment]
Looking through the logs it seems to have failed storing the image after downloading. This can happen if another program locks the chapter/manga file, e.g. DropBox.

**Comment by DDraper95** [comment]
Ah, google drive then wanted away to sinc it between my pc and laptop. Worked fine for a few days

**Comment by jrjparks** [comment]
I've been using OneDrive. I'll look into a better way to handle other sync services. The odd thing is it will only fail to write to the file after 30 minutes have passed, meaning GDrive was holding that file for a long time / not releasing it's hold.
