### ISSUE TITLE
Images don't appear after downloading form Mangahere

### ISSUE THREAD

**Issue by dxxrock13** [jrjparks/myManga#52]
[here's the screenshot from the app](https://postimg.org/image/wqtcvgedn/)
[here's another one from the folder](https://postimg.org/image/4d4kcsp2d/)

as you can see from the screenshots above, i was able to download the chapter but the images don't appear when i open it. I already tried re-downloading the chapter yet the images still don't appear. Can you fix this problem, please ?

**Comment by jrjparks** [comment]
MangaHere recently changed how images are downloaded. I have a fix that I can upload in a few hours.

**Comment by jrjparks** [comment]
See [release 3.0.5994.33342dev](https://github.com/jrjparks/myManga/releases/tag/3.0.5994.33342dev) for fixed MangaHere dll download.

**Comment by dxxrock13** [comment]
thanks dude. it works perfectly now
