### ISSUE TITLE
Sunday Webry uses PUBLUS Reader to encrypt manga pages. Can support for it be added?

### ISSUE THREAD

**Issue by JB2448** [jrjparks/myManga#55]
https://www.sunday-webry.com, an online manga service that posts new chapters of series like Pokémon Special, just went into maintenance to upgrade its reading software to https://gl.access-company.com/products/dpub/publus_reader/ which makes pages scrambled like this when attempting to save them: 
![image](https://user-images.githubusercontent.com/20935099/28844438-9a124eb4-76d2-11e7-8595-7bd6901a15a0.png)
What are our options for the site? Is it possible to decrypt the files or at least download them at their native resolution by spoofing that resolution on a desktop and PrintScreen and cropping in myManga, or are there any other options? If so, can support for the site be added to myManga?

**Comment by jrjparks** [comment]
While this would be an interesting challenge, I will not be adding this site. Someone has probably already figured this out if you search for it.
